import './globals.css'
import localFont from 'next/font/local'
import NavBar from "@/app/_comp/nav/navBar";


const SFPro = localFont({
  src: [
    {
      path: '../../public/SFPro/regular.otf',
      weight: '500',
      style: 'normal',
      variable: '--regular'
    },
    {
      path: '../../public/SFPro/medium.otf',
      weight: '600',
      style: 'normal',
      variable: '--medium'
    },
    {
      path: '../../public/SFPro/semi_bold.otf',
      weight: '700',
      style: 'normal',
      variable: '--semi_bold'
    },
    {
      path: '../../public/SFPro/bold.otf',
      weight: '800',
      style: 'normal',
      variable: '--bold'
    },
  ]
})



export const metadata = {
  title: 'Facebook Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SFPro.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
